# Config.yml

# Site settings
title: Architech
description: Leading Roblox Tech Group

# Theme settings
theme: jekyll-theme-minimal-dark

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
