# Config.yml

# Site settings
title: Architech
description: Leading Roblox Tech Group
remote_theme: pages-themes/minimal@v0.2.0
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
